---
title: Example Page
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  shows:
    title: Shows
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: Shows
  values:
    start-date: ''
    doors-date: ''
    ticket-url: ''
email: info@voltagearc.com
description: This is an example page.
baseurl: "/"
url: https://example.voltagearc.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- resources
