---
title: Example Page
timezone: Europe/Berlin
collections:
  frontpage:
    title: Frontpage
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@voltagearc.com
description: This is an example page.
baseurl: "/"
url: https://example.voltagearc.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- resources
