---
title: Example Page
timezone: Europe/Berlin
collections:
  photos:
    title: Photos
    output: false
  posts:
    title: Posts
    output: true
  shows:
    title: Shows
    output: false
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: false
defaults:
- scope:
    path: ''
    type: shows
  values:
    start-date: ''
    doors-date: ''
    ticket-url: ''
    street: ''
    city: ''
    canton: ''
    zip: ''
    venue-name: ''
- scope:
    path: ''
    type: videos
  values:
    yt-id: ''
    thumbnail-base: https://img.youtube.com/vi/
    thumbnail-quality: "/maxresdefault.jpg"
    embed-base: https://www.youtube.com/embed/
    embed-options: "?autoplay=1"
- scope:
    path: ''
    type: photos
  values:
    file: ''
    ig-url: ''
email: info@voltagearc.com
description: This is an example page.
baseurl: "/"
url: https://example.voltagearc.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- resources
- node_modules
